export const NETWORK_ERROR = "NETWORK_ERROR";

export const CUSTOMER_REGISTER = "CUSTOMER_REGISTER";
export const CUSTOMER_REGISTER_FAIL = "CUSTOMER_REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CUSTOMER_LOGIN = "CUSTOMER_LOGIN";
export const CUSTOMER_LOGIN_FAIL = "CUSTOMER_LOGIN_FAIL";

export const USER_AUTH = "USER_AUTH";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMER_ADDRESS = "GET_CUSTOMER_ADDRESS";
export const UPDATE_CUSTOMER_PROFILE = "UPDATE_CUSTOMER_PROFILE";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_MORE_PRODUCTS = "GET_MORE_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SUB_CATEGORIES_BY_CATEGORY = "GET_SUB_CATEGORIES_BY_CATEGORY";

export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const RESET_PRODUCTS_BY_CATEGORY = "RESET_PRODUCTS_BY_CATEGORY";
export const GET_PRODUCTS_BY_SUB_CATEGORY = "GET_PRODUCTS_BY_SUB_CATEGORY";
export const GET_MORE_PRODUCTS_BY_SUB_CATEGORY =
  "GET_MORE_PRODUCTS_BY_SUB_CATEGORY";
export const CLEAR_MORE_PRODUCTS_BY_SUB_CATEGORY =
  "CLEAR_MORE_PRODUCTS_BY_SUB_CATEGORY";

export const LOGOUT = "LOGOUT";

export const ADD_TO_CART = "ADD_TO_CART";
export const GET_USER_CART_ITEMS = "GET_USER_CART_ITEMS";
export const DECREASE_CART_PRODUCT_QUANTITY = "DECREASE_CART_PRODUCT_QUANTITY";
export const REMOVE_CART_PRODUCT = "REMOVE_CART_PRODUCT";

export const MAKE_ORDER_SUCCESS = "MAKE_ORDER_SUCCESS";
export const MAKE_ORDER_FAIL = "MAKE_ORDER_FAIL";

export const GET_ORDERS = "GET_ORDERS";
export const CALCULATE_SHIPPING_FEE = "CALCULATE_SHIPPING_FEE";

export const GET_LANGUAGE = "GET_LANGUAGE";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
